version: '3'
services:
  client:
    container_name: todos-client
    restart: always
    build: ./client
    ports:
      - '80:80'
    links:
      - server
  server:
    container_name: todos-server
    restart: always
    build: ./server
    ports:
      - '80:5000'
