version: '3.7'

services:
  todos-client-swarm:
    image: modanisachallenge_client:latest
    ports:
      - '8080:80'
  todos-server-swarm:
    image: modanisachallenge_server:latest
    ports:
      - '5000:5000'
